users/urls.py
from django.urls import re_path

from .views import profile

app_name = 'users'
urlpatterns = [
    re_path(r'^$', profile, name='profile'),
]

templates/includes/footer.html
<footer class="ftco-footer ftco-bg-dark ftco-section">
  <div class="container">
    <div class="row mb-5">
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Adventure</h2>
          <p>If you are an adventurous person connect with our website via different platforms to avail the services.</p>
          <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
          </ul>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4 ml-md-4">
          <h2 class="ftco-heading-2">Information</h2>
          <ul class="list-unstyled">
            <li><a href="#" class="py-2 d-block">About Us</a></li>
            <li><a href="#" class="py-2 d-block">Online enquiry</a></li>
            <li><a href="#" class="py-2 d-block">Call Us</a></li>
            <li><a href="#" class="py-2 d-block">General enquiries</a></li>
            <li><a href="#" class="py-2 d-block">Booking Conditions</a></li>
            <li><a href="#" class="py-2 d-block">Privacy and Policy</a></li>
            <li><a href="#" class="py-2 d-block">Refund policy</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md">
         <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Experience</h2>
          <ul class="list-unstyled">
            <li><a href="#" class="py-2 d-block">Beach</a></li>
            <li><a href="#" class="py-2 d-block">Adventure</a></li>
            <li><a href="#" class="py-2 d-block">Wildlife</a></li>
            <li><a href="#" class="py-2 d-block">History</a></li>
            <li><a href="#" class="py-2 d-block">Nature</a></li>

          </ul>
        </div>
      </div>
      <div class="col-md">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Have a Questions?</h2>
          <div class="block-23 mb-3">
            <ul>
              <li><span class="icon icon-map-marker"></span><span class="text">171-A Ali Town Raiwind Road, Lahore</span></li>
              <li><a href="#"><span class="icon icon-phone"></span><span class="text">+923418669572</span></a></li>
              <li><a href="#"><span class="icon icon-envelope"></span><span class="text">waseemhaider124@gmail.com</span></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

  </div>
</footer>

templates/includes/header.html
{% load static i18n %}
{% load account startswith %}

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">
      {% if not hide_navbar_brand %}
        {% if navbar_brand_text %}
          {{ navbar_brand_text }}
        {% else %}
          Tickets4You
        {% endif %}
      {% endif %}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> Menu
    </button>

    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        {% if toggle_the_navbar %}

        <li class="nav-item {% if request.path == '/' %}active{% endif %}"><a href="{% url 'index' %}" class="nav-link">Home</a></li>
        <li class="nav-item"><a href="about.html" class="nav-link">About</a></li>
        <li class="nav-item"><a href="places.html" class="nav-link">Places</a></li>
        <li class="nav-item {% if request.path|startswith:'/hotels/' %}active{% endif %}"><a href="{% url 'hotels' %}" class="nav-link">Hotels</a></li>
        <li class="nav-item {% if request.path|startswith:'/blog/' %}active{% endif %}"><a href="{% url 'blog' %}" class="nav-link">Blog</a></li>
        <li class="nav-item {% if request.path|startswith:'/contact/' %}active{% endif %}"><a href="{% url 'contact' %}" class="nav-link">Contact</a></li>

        {% else %}

        <li class="nav-item {% if request.path == '/' %}active{% endif %}"><a href="{% url 'index' %}" class="nav-link"><b>Home</b></a></li>
        <li class="nav-item {% if request.path|startswith:'/offers/' %}active{% endif %}"><a href="{% url 'offers' %}" class="nav-link"><b>Offers</b></a></li>
        <li class="nav-item {% if request.path|startswith:'/companies/' %}active{% endif %}"><a href="{% url 'companies' %}" class="nav-link"><b>Travelling Companies</b></a></li>
        <li class="nav-item {% if request.path|startswith:'/feedback/' %}active{% endif %}"><a href="{% url 'feedback' %}" class="nav-link"><b>Feedback</b></a></li>

        <li class="nav-item {% if request.path|startswith:'/contact/' %}active{% endif %}"><a href="{% url 'contact' %}" class="nav-link"><b>Contact Us</b></a></li>

        {% if request.user.is_authenticated %}
          <li class="nav-item {% if request.path|startswith:'/profile/' %}active{% endif %}"><a href="{% url 'users:profile' %}" class="nav-link"><b>Profile</b></a></li>
          <li class="nav-item"><a href="{% url 'account_logout' %}" class="nav-link"><b>Logout</b></a></li>
        {% else %}
          <li class="nav-item"><a href="{% url 'account_signup' %}" class="nav-link"><b>Register</b></a></li>
          <li class="nav-item"><a href="{% url 'account_login' %}" class="nav-link"><b>Login</b></a></li>
        {% endif %}

      {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/includes/messages.html
{% if messages %}
<div class="container mt-4 px-4">
  {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message|safe }}
    </div>
  {% endfor %}
</div>
{% endif %}